services:
  # A Docker web service
  - type: web
    name: melayumate-fastapi-ml
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: hypercorn main:app --bind 0.0.0.0:10000 --workers 4